export const GET_PRODUCTS_REQUEST = 'GET_PRODUCTS_REQUEST';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAIL = 'GET_PRODUCTS_FAIL';

export const GET_PRODUCTS_DETAILS_REQUEST = 'GET_PRODUCTS_DETAILS_REQUEST';
export const GET_PRODUCTS_DETAILS_SUCCESS = 'GET_PRODUCTS_DETAILS_SUCCESS';
export const GET_PRODUCTS_DETAILS_FAIL = 'GET_PRODUCTS_DETAILS_FAIL';

export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const CART_RESET = 'CART_RESET';

export const ADD_PRODUCT = 'ADD_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const ADD_PRODUCT_FAIL = 'ADD_PRODUCT_FAIL';
export const DELETE_PRODUCT_FAIL = 'DELETE_PRODUCT_FAIL';